<a href="https://colab.research.google.com/github/sherlinvarshitha/Generative-AI/blob/main/ASS_W8_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(1 ponto) Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library
2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.
3. (1 ponto) Build the application by loading the saved ANN model.
Tabela 1: ANN Architecture
Layer Neurons Activation Function
Hidden Layer - 1 16 relu
Hidden Layer - 2 20 relu
Hidden Layer - 3 25 relu
Hidden Layer - 4 10 relu
Tabela 2: Training Parameters
epochs batch size error metric Optimizer
100 64 accuracy adadelta

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
data = pd.read_csv("/content/winequality-red.csv")  # Update with actual path if needed

In [ ]:

X = data.drop("quality", axis=1)
y = data["quality"]

In [ ]:
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust for classification


In [ ]:
y = pd.get_dummies(y)  # One-hot encoding for ANN classification

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(y.shape[1], activation='softmax')  # Output layer
])


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.4089 - loss: 1.1009 - val_accuracy: 0.3969 - val_loss: 1.0816
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.3840 - loss: 1.1082 - val_accuracy: 0.3969 - val_loss: 1.0814
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3824 - loss: 1.1154 - val_accuracy: 0.3969 - val_loss: 1.0813
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.4086 - loss: 1.1052 - val_accuracy: 0.3969 - val_loss: 1.0811
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3868 - loss: 1.0929 - val_accuracy: 0.3969 - val_loss: 1.0809
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3948 - loss: 1.0955 - val_accuracy: 0.3969 - val_loss: 1.0808
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4012 - loss: 1.0933 - val_accuracy: 0.3969 - val_loss: 1.0806
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4026 - loss: 1.0937 - val_accuracy: 0.

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3750 - loss: 1.0792  
Test Accuracy: 0.3843750059604645


In [ ]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test.values, axis=1)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step  


In [ ]:
conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_true, y_pred_classes))

Confusion Matrix:
 [[  2 139   0]
 [ 11 121   0]
 [  2  45   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.13      0.01      0.03       141
           1       0.40      0.92      0.55       132
           2       0.00      0.00      0.00        47

    accuracy                           0.38       320
   macro avg       0.18      0.31      0.19       320
weighted avg       0.22      0.38      0.24       320



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
model.save("wine_quality_model.h5")

In [ ]:
def load_model():
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    return loaded_model

In [ ]:
loaded_model = load_model()
predictions = loaded_model.predict(X_test[:5])
print("Sample Predictions:", np.argmax(predictions, axis=1))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
Sample Predictions: [1 1 1 1 1]
